### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by jie666-6** [multiply-org/sar-pre-processing#18]
Hi, there is an error when I try to use 'python setup.py install' and I do not know how to solve it. Is there anyone can help? Thanks in advance

Here is the error information:
(sensarp-env) C:\Workplace\05software\sar-pre-processing-master\sar-pre-processing-master>python setup.py develop
running develop
C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing multiply_sar_pre_processing.egg-info\PKG-INFO
writing dependency_links to multiply_sar_pre_processing.egg-info\dependency_links.txt
writing requirements to multiply_sar_pre_processing.egg-info\requires.txt
writing top-level names to multiply_sar_pre_processing.egg-info\top_level.txt
reading manifest file 'multiply_sar_pre_processing.egg-info\SOURCES.txt'
adding license file 'LICENSE.rst'
adding license file 'AUTHORS.rst'
writing manifest file 'multiply_sar_pre_processing.egg-info\SOURCES.txt'
running build_ext
Creating c:\users\jiez\anaconda3\envs\sensarp-env\lib\site-packages\multiply-sar-pre-processing.egg-link (link to .)
Removing multiply-sar-pre-processing 0.1 from easy-install.pth file
Adding multiply-sar-pre-processing 0.1 to easy-install.pth file

Installed c:\workplace\05software\sar-pre-processing-master\sar-pre-processing-master
Processing dependencies for multiply-sar-pre-processing==0.1
Searching for m2r
Reading https://pypi.org/simple/m2r/
Downloading https://files.pythonhosted.org/packages/94/65/fd40fbdc608298e760affb95869c3baed237dfe5649d62da1eaa1deca8f3/m2r-0.3.1.tar.gz#sha256=aafb67fc49cfb1d89e46a3443ac747e15f4bb42df20ed04f067ad9efbee256ab
Best match: m2r 0.3.1
Processing m2r-0.3.1.tar.gz
Writing C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\setup.cfg
Running m2r-0.3.1\setup.py -q bdist_egg --dist-dir C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\egg-dist-tmp-imzwnd47
Traceback (most recent call last):
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\setup.py", line 13, in <module>

  File "C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\m2r.py", line 51, in <module>
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Workplace\05software\sar-pre-processing-master\sar-pre-processing-master\setup.py", line 29, in <module>
    setup(name='multiply-sar-pre-processing',
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\develop.py", line 130, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\pkg_resources\__init__.py", line 815, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\pkg_resources\__init__.py", line 851, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\pkg_resources\__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\pkg_resources\__init__.py", line 1135, in obtain
    return installer(requirement)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\command\easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 190, in setup_context
    with save_modules():
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\JieZ\anaconda3\envs\sensarp-env\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\setup.py", line 13, in <module>

  File "C:\Users\JieZ\AppData\Local\Temp\easy_install-h3pc2mwd\m2r-0.3.1\m2r.py", line 51, in <module>
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

**Comment by McWhity** [comment]
It seems to be a problem with specific dependencies of module m2r, mistune and nbconvert. These packages are needed to create the ReadtheDocs documentation. Thus, they are not needed for the processing capabilities.
Therefore, a quick fix should be a removal of m2r and mistune from the requirements file ([/docs/requirements.txt](https://github.com/multiply-org/sar-pre-processing/blob/master/docs/requirements.txt)). The processing chain and the juypter notebooks should be working.
I hope that helps. I will have a more detailed look next week.
