### ISSUE TITLE
Error message: does not have enough valid GCPs for the warp

### ISSUE THREAD

**Issue by simtrax** [multiply-org/sar-pre-processing#20]
Hi,

I have continued to use the library with good results.
But for some reason I have started to get som issues lately.

I have cloned the branch `dev` to be certain that I have no modifications in the code.

My config looks like this (full paths removed):
```
---
gpt: my-path/bin/gpt
input_folder: my-path/zipped
output_folder: my-path/zipped/results
region:
    subset: 'yes'
    ul:
        lat: 58.50889732892996
        lon: 15.41565645110719
    lr:
        lat: 58.50338422634605
        lon: 15.434550918769634
single_file: 'no'
speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '3'
use_user_defined_graphs: 'no'
year: '2023'
```

And the output looks like this:
```
INFO:root:Found files within input folder: 3
INFO:root:Number of found files for year 2023: 3
INFO:root:area of interest not specified
INFO:root:Number of found files that were double processed: 0.0
INFO:root:Number of found files with border issues: 0
start step 1
INFO:root:area of interest specified
INFO:root:normalisation angle not specified, default value of 35 is used for processing
INFO:ComponentProgress:0
INFO:ComponentProgress:0
INFO:root:Process S1A_IW_SLC__1SDV_20230601T164609_20230601T164636_048795_05DE38_29F6.zip with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
.12%.24%.36%.48%.60%.72%..82%.. done.
INFO:root:0
INFO:ComponentProgress:33
INFO:ComponentProgress:33
INFO:root:Process S1A_IW_SLC__1SDV_20230613T164609_20230613T164636_048970_05E391_2AC7.zip with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
.12%.24%.36%.48%.60%.72%..82%.. done.
INFO:root:0
INFO:ComponentProgress:66
INFO:ComponentProgress:66
INFO:root:Process S1A_IW_SLC__1SDV_20230625T164610_20230625T164637_049145_05E8E0_A532.zip with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
.12%.24%.36%.48%.60%.72%..82%.. done.
INFO:root:0
start step 2
INFO:ComponentProgress:0
INFO:ComponentProgress:0
INFO:root:Scene 1 of 3
INFO:root:Process S1A_IW_SLC__1SDV_20230601T164609_20230601T164636_048795_05DE38_29F6_GC_RC_No_Su.dim with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
11%22%33%45%56%67%....77%89%WARNING: org.esa.s1tbx.insar.gpf.coregistration.WarpOp: sigma0_vv_kelln_normalisation_slv1_01Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_normalisation_slv2_01Jun2023 does not have enough valid GCPs for the warp
sigma0_vv_kelln_slv3_01Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_slv4_01Jun2023 does not have enough valid GCPs for the warp
Sigma0_VH_slv5_01Jun2023 does not have enough valid GCPs for the warp
Sigma0_VV_slv6_01Jun2023 does not have enough valid GCPs for the warp
elevation_slv7_01Jun2023 does not have enough valid GCPs for the warp
latitude_slv8_01Jun2023 does not have enough valid GCPs for the warp
longitude_slv9_01Jun2023 does not have enough valid GCPs for the warp
localIncidenceAngle_slv10_01Jun2023 does not have enough valid GCPs for the warp
projectedLocalIncidenceAngle_slv11_01Jun2023 does not have enough valid GCPs for the warp
incidenceAngleFromEllipsoid_slv12_01Jun2023 does not have enough valid GCPs for the warp

 done.
-- org.jblas INFO Deleting /tmp/jblas4948606569346391204/libquadmath-0.so
-- org.jblas INFO Deleting /tmp/jblas4948606569346391204/libgfortran-4.so
-- org.jblas INFO Deleting /tmp/jblas4948606569346391204/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas4948606569346391204/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas4948606569346391204
INFO:root:0
INFO:root:2023-09-28 14:02:58.930132
INFO:ComponentProgress:33
INFO:ComponentProgress:33
INFO:root:Scene 2 of 3
INFO:root:Process S1A_IW_SLC__1SDV_20230613T164609_20230613T164636_048970_05E391_2AC7_GC_RC_No_Su.dim with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
11%22%33%45%56%67%....77%89%WARNING: org.esa.s1tbx.insar.gpf.coregistration.WarpOp: sigma0_vv_kelln_normalisation_slv1_13Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_normalisation_slv2_13Jun2023 does not have enough valid GCPs for the warp
sigma0_vv_kelln_slv3_13Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_slv4_13Jun2023 does not have enough valid GCPs for the warp
Sigma0_VH_slv5_13Jun2023 does not have enough valid GCPs for the warp
Sigma0_VV_slv6_13Jun2023 does not have enough valid GCPs for the warp
elevation_slv7_13Jun2023 does not have enough valid GCPs for the warp
latitude_slv8_13Jun2023 does not have enough valid GCPs for the warp
longitude_slv9_13Jun2023 does not have enough valid GCPs for the warp
localIncidenceAngle_slv10_13Jun2023 does not have enough valid GCPs for the warp
projectedLocalIncidenceAngle_slv11_13Jun2023 does not have enough valid GCPs for the warp
incidenceAngleFromEllipsoid_slv12_13Jun2023 does not have enough valid GCPs for the warp

 done.
-- org.jblas INFO Deleting /tmp/jblas6722729105166058461/libquadmath-0.so
-- org.jblas INFO Deleting /tmp/jblas6722729105166058461/libgfortran-4.so
-- org.jblas INFO Deleting /tmp/jblas6722729105166058461/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas6722729105166058461/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas6722729105166058461
INFO:root:0
INFO:root:2023-09-28 14:03:03.132768
INFO:ComponentProgress:66
INFO:ComponentProgress:66
INFO:root:Scene 3 of 3
INFO:root:Process S1A_IW_SLC__1SDV_20230625T164610_20230625T164637_049145_05E8E0_A532_GC_RC_No_Su.dim with SNAP.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
INFO: org.esa.snap.core.datamodel.Product: raster height 45 not equal to 46
11%22%33%45%56%67%....77%89%WARNING: org.esa.s1tbx.insar.gpf.coregistration.WarpOp: sigma0_vv_kelln_normalisation_slv1_25Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_normalisation_slv2_25Jun2023 does not have enough valid GCPs for the warp
sigma0_vv_kelln_slv3_25Jun2023 does not have enough valid GCPs for the warp
sigma0_vh_kelln_slv4_25Jun2023 does not have enough valid GCPs for the warp
Sigma0_VH_slv5_25Jun2023 does not have enough valid GCPs for the warp
Sigma0_VV_slv6_25Jun2023 does not have enough valid GCPs for the warp
elevation_slv7_25Jun2023 does not have enough valid GCPs for the warp
latitude_slv8_25Jun2023 does not have enough valid GCPs for the warp
longitude_slv9_25Jun2023 does not have enough valid GCPs for the warp
localIncidenceAngle_slv10_25Jun2023 does not have enough valid GCPs for the warp
projectedLocalIncidenceAngle_slv11_25Jun2023 does not have enough valid GCPs for the warp
incidenceAngleFromEllipsoid_slv12_25Jun2023 does not have enough valid GCPs for the warp

 done.
-- org.jblas INFO Deleting /tmp/jblas3138609256322867964/libquadmath-0.so
-- org.jblas INFO Deleting /tmp/jblas3138609256322867964/libgfortran-4.so
-- org.jblas INFO Deleting /tmp/jblas3138609256322867964/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas3138609256322867964/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas3138609256322867964
INFO:root:0
INFO:root:2023-09-28 14:03:07.424898
start step 3
INFO:ComponentProgress:0
INFO:ComponentProgress:0
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
...12%...24%...36%...48%...60%...72%...84%.. done.
java.lang.IllegalArgumentException: The given name 'Master: 01Jun2023.0' is not a valid node name.
	at org.esa.snap.core.datamodel.ProductNode.setNodeName(ProductNode.java:115)
	at org.esa.snap.core.datamodel.ProductNode.setName(ProductNode.java:102)
	at org.esa.snap.dataio.netcdf.metadata.profiles.cf.CfMetadataPart.makeCompatible(CfMetadataPart.java:111)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.esa.snap.dataio.netcdf.metadata.profiles.cf.CfMetadataPart.makeCompatible(CfMetadataPart.java:117)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.esa.snap.dataio.netcdf.metadata.profiles.cf.CfMetadataPart.makeCompatible(CfMetadataPart.java:117)
	at org.esa.snap.dataio.netcdf.metadata.profiles.cf.CfMetadataPart.preEncode(CfMetadataPart.java:93)
	at org.esa.snap.dataio.netcdf.NetCdfWriteProfile.writeProduct(NetCdfWriteProfile.java:50)
	at org.esa.snap.dataio.netcdf.DefaultNetCdfWriter.writeProductNodesImpl(DefaultNetCdfWriter.java:65)
	at org.esa.snap.core.dataio.AbstractProductWriter.writeProductNodes(AbstractProductWriter.java:111)
	at org.esa.snap.core.gpf.common.WriteOp.doExecute(WriteOp.java:315)
	at org.esa.snap.core.gpf.internal.OperatorContext.executeOperator(OperatorContext.java:1300)
	at org.esa.snap.core.gpf.Operator.execute(Operator.java:153)
	at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:198)
	at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:128)
	at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:86)
	at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:547)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:391)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:287)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
	at org.esa.snap.core.gpf.main.GPT.run(GPT.java:59)
	at org.esa.snap.core.gpf.main.GPT.main(GPT.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.esa.snap.runtime.Launcher1159904018.main(Unknown Source)

Error: The given name 'Master: 01Jun2023.0' is not a valid node name.
INFO:root:1
INFO:root:2023-09-28 14:03:12.521057
INFO:ComponentProgress:33
INFO:ComponentProgress:33
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
...12%...24%...36%...48%...60%...72%...84%.4696 [main] INFO serverStartup - Nc4Iosp: NetCDF-4 C library loaded (jna_path='my-path/.snap/auxdata/netcdf_natives/9.0.6/amd64', libname='netcdf').
4700 [main] INFO serverStartup - NetcdfLoader: set log level: old=0 new=0
4700 [main] INFO serverStartup - Nc4Iosp: set log level: old=0 new=0
. done.
INFO:root:0
INFO:root:2023-09-28 14:03:21.899895
INFO:ComponentProgress:66
INFO:ComponentProgress:66
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
...12%...24%...36%...48%...60%...72%...84%.4538 [main] INFO serverStartup - Nc4Iosp: NetCDF-4 C library loaded (jna_path='my-path/.snap/auxdata/netcdf_natives/9.0.6/amd64', libname='netcdf').
4542 [main] INFO serverStartup - NetcdfLoader: set log level: old=0 new=0
4542 [main] INFO serverStartup - Nc4Iosp: set log level: old=0 new=0
. done.
INFO:root:0
INFO:root:2023-09-28 14:03:31.013782
```

The three scenes have the same orbitNbr and are situated like this:
![image](https://github.com/multiply-org/sar-pre-processing/assets/10018647/53e7240d-c62b-481d-9304-25db6c89f11c)

Any tips would be appreciated.

Kind regards,
Simon

**Comment by McWhity** [comment]
The title of your Issue 
>  Error message: does not have enough valid GCPs for the warp #20 

is actually not an error but a warning. The specified subset area is too small.  Hence, to less valid GCPs (Ground Control Points) can be found for the coregistration process. If you increase the area of interest the warning should disappear.

The reason why the processing fails is the following error 
> ``Error: The given name 'Master: 01Jun2023.0' is not a valid node name.

I suspect that the ".0" behind the date is the reason why it fails. I had a quick test run and I could reproduce your error if I use the last SNAP version (9.0.x). If I use version 8.0.x the error does not exist. It seems that between version 8.0 and 9.0 something how SNAP handles band naming has changed. I will probably need some time to solve/investigate the issue. I will keep you posted.

**Comment by simtrax** [comment]
> The title of your Issue
> 
> > Error message: does not have enough valid GCPs for the warp #20
> 
> is actually not an error but a warning. The specified subset area is too small. Hence, to less valid GCPs (Ground Control Points) can be found for the coregistration process. If you increase the area of interest the warning should disappear.
> 
> The reason why the processing fails is the following error
> 
> > ``Error: The given name 'Master: 01Jun2023.0' is not a valid node name.
> 
> I suspect that the ".0" behind the date is the reason why it fails. I had a quick test run and I could reproduce your error if I use the last SNAP version (9.0.x). If I use version 8.0.x the error does not exist. It seems that between version 8.0 and 9.0 something how SNAP handles band naming has changed. I will probably need some time to solve/investigate the issue. I will keep you posted.

Hi!

Thank you for the reply, increasing the area definitely worked better.

/Simon
